### ISSUE TITLE
elasticSearch_crud.py - 곧장기부 insert 실패 오류 

### ISSUE THREAD

**Issue by im-shung** [2E2I/donation-crawler#25]
```
capstone2e2i_gmail_com@es-instance-1:~/donation-crawler$ python3 elasticSearch/elasticSearch_crud.py 
elasticSearch/elasticSearch_crud.py:35: ElasticsearchWarning: [types removal] Specifying types in bulk requests is d
eprecated.
  res = helpers.bulk(es, data)
happybean insert : (861, [])
kakao insert : (123, [])
Traceback (most recent call last):
  File "elasticSearch/elasticSearch_crud.py", line 41, in <module>
    initData()
  File "elasticSearch/elasticSearch_crud.py", line 35, in initData
    res = helpers.bulk(es, data)
  File "/home/capstone2e2i_gmail_com/.local/lib/python3.6/site-packages/elasticsearch/helpers/actions.py", line 525,
 in bulk
    client, actions, ignore_status=ignore_status, *args, **kwargs  # type: ignore[misc]
  File "/home/capstone2e2i_gmail_com/.local/lib/python3.6/site-packages/elasticsearch/helpers/actions.py", line 448,
 in streaming_bulk
    **kwargs,
  File "/home/capstone2e2i_gmail_com/.local/lib/python3.6/site-packages/elasticsearch/helpers/actions.py", line 355,
 in _process_bulk_chunk
    yield from gen
  File "/home/capstone2e2i_gmail_com/.local/lib/python3.6/site-packages/elasticsearch/helpers/actions.py", line 274,
 in _process_bulk_chunk_success
    raise BulkIndexError(f"{len(errors)} document(s) failed to index.", errors)
elasticsearch.helpers.BulkIndexError: 6 document(s) failed to index.
```
타입 오류인지 안들어가네.. 로컬에서 테스트 한 다음에 고치겠음

**Comment by im-shung** [comment]
로컬에선 잘 들어가는데 인스턴스에서 실행하면 오류나네 ;-;
